name: Main Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build-test:
    uses: ./.github/workflow/reusable-build-test.yml
    with:
      node_version: "20"
      run_tests: true

  docker:
    needs: build-test

    uses:
