name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node.js Version"
        required: true
        type: string

    run_tests:
      description: "Run Tests"
      required: false
      default: true
      type: boolean

    outputs:
      test_result:
        description: "Build/Test Result"
        value: ${{ jobs.build-test.outputs.test_result }}

jobs:
  build-test:
    runs-on: ubuntu-latest

    outputs:
      test_result: ${{ steps.result.outputs.test_result }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Pull Docker Image
        run: docker pull dockeratharva29/tetris-game-app:latest

      - name: Run Docker Container
        if: ${{ inputs.run_tests }}
        run: | 
          docker run -d \
            --name tetris-app \
            -p 3000:80 \
            dockeratharva29/tetris-game-app:latest

      - name: Wait for Application
        if: ${{ inputs.run_test }}
        run: sleep 10

      - name: Run Tests
        if: ${{ inputs.run_tests }}
        run: ./test.sh

      - name: Set Test Result
        id: result
        if: success()
        run: echo "test_result=passed" >> $GITHUB_OUTPUT

      - name: Stop and Remove Container
        if: always() && inputs.run_tests
        run: |
          docker stop tetris-app || true
          docker rm tetris-app || true
